
services:
  orders:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: orders
    env_file:
      - ./apps/orders/.env.docker
    ports:
      - "${ORDERS_SERVICE_PORT:-3003}:${ORDERS_SERVICE_PORT:-3003}"
    environment:
      PORT: ${DO_PORT:-3003}
      MONGO_DATABASE_URL: mongodb://${MONGO_ROOT_USERNAME:-root}:${MONGO_ROOT_PASSWORD}@mongodb-primary:27017,mongodb-secondary:27017/ordering-app?replicaSet=rs0&authSource=admin
    command: sh -c "node dist/apps/orders/main"
    depends_on:
      - mongodb-primary
      - mongodb-secondary
      - mongodb-arbiter
      - rabbitmq
      - billing
      - auth
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/node_modules
    restart: unless-stopped

  auth:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: auth
    env_file:
      - ./apps/auth/.env.docker
    ports:
      - "${AUTH_SERVICE_PORT:-3004}:${AUTH_SERVICE_PORT:-3004}"
    environment:
      PORT: ${DO_PORT:-3004}
      MONGO_DATABASE_URL: mongodb://${MONGO_ROOT_USERNAME:-root}:${MONGO_ROOT_PASSWORD}@mongodb-primary:27017,mongodb-secondary:27017/ordering-app?replicaSet=rs0&authSource=admin
    command: sh -c "node dist/apps/auth/main"
    restart: unless-stopped
    depends_on:
      - mongodb-primary
      - mongodb-secondary
      - mongodb-arbiter
      - rabbitmq

  billing:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: billing
    env_file:
      - ./apps/billing/.env.docker
    environment:
      PORT: ${BILLING_SERVICE_PORT:-3005}
    command: sh -c "node dist/apps/billing/main"
    restart: unless-stopped   
    depends_on:
      - mongodb-primary
      - mongodb-secondary
      - mongodb-arbiter
      - rabbitmq
      - auth

  mongodb-primary:
    image: docker.io/bitnami/mongodb@sha256:b69e28a2017af190348f14ebc279dc074d58f511f691ecec8ca8a468276e7cb6
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_ROOT_USER=${MONGO_ROOT_USERNAME:-root}
      - MONGODB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - 'mongodb_master_data:/bitnami/mongodb'
    ports:
      - "27018:27017"

  rabbitmq:
    image: rabbitmq:4.2.5-management-alpine
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mongodb-secondary:
    image: docker.io/bitnami/mongodb@sha256:b69e28a2017af190348f14ebc279dc074d58f511f691ecec8ca8a468276e7cb6
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_USER=${MONGO_ROOT_USERNAME:-root}
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

  mongodb-arbiter:
    image: docker.io/bitnami/mongodb@sha256:b69e28a2017af190348f14ebc279dc074d58f511f691ecec8ca8a468276e7cb6
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_USER=${MONGO_ROOT_USERNAME:-root}
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

volumes:
  rabbitmq_data:
  mongodb_master_data:
    driver: local
